---
title: "Incidence of TAK by age, sex, and region"
author: "Stephanie J Lax"
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: hide
  
---

```{r setup, include=FALSE}
#setup markdown
knitr::opts_chunk$set(echo = TRUE)

#load packages at first use
# install.packages("tidyverse")
# install.packages("knitr")
# install.packages("kableExtra")

library(tidyverse)
library(knitr)
library(kableExtra)

#set working directory
setwd("[redacted]")
```

### Data

```{r TAK_incidence}
incidence_by_imd <- read.csv("[redacted]~/ccu075_01_M314_inc_rates_per_m_imd_20241014.csv") %>%
  select(-X) %>%
  mutate(IMD = as.character(IMD))

incidence_by_imd %>%
  kable(booktabs = TRUE, align = "l", col.names = c("Index of multiple deprivation",
                                                    "Cases of M31.4",
                                                    "Percentage of total cases",
                                                    "Population", 
                                                    "Crude incidence rate*",
                                                    "Poisson 95% CI (lower bound)",
                                                    "Poisson 95% CI (upper bound)")
        )

incidence_ratios <- read.csv("[redacted]~/ccu075_01_M314_inc_ratios_IMD_20241014.csv") %>%
  select(-X) %>% 
  mutate(Group = gsub("IMD", "", Group)) %>% 
  rename(IMD = Group)

incidence_data_with_crude_ratios <- left_join(incidence_by_imd, incidence_ratios, by="IMD") 

adjusted_ratios <- incidence_ratios %>%
  filter(grepl("\\*", IMD)) %>%
  mutate(IMD = gsub("\\*", "", IMD)) %>%
  rename(aOR = OR,
         aLower_CI = Lower_CI,
         aUpper_CI = Upper_CI)

incidence_data_with_adjusted_ratios <- left_join(incidence_data_with_crude_ratios, adjusted_ratios, by="IMD") 

incidence_data_with_adjusted_ratios %>%
  kable(booktabs = TRUE, align = "l")

#write.csv(incidence_data_with_adjusted_ratios, "20241017_incidence_by_age_sex_imd.csv")
```

*NB: Counts rounded to nearest 5 to comply with NHSE disclosure controls. Total cases rounded based on the sum of the unrounded counts.*

### Version

```{r version}
sessionInfo()
```