---
title: "Incidence estimates for Takayasu arteritis in England"
author: "SJ Lax"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
  pdf_document: default
---

### Setup

```{r setup}
#install packages at first use
#install.packages("tidyverse", repos = "https://packages.sde.digital.nhs.uk/repository/cran-mirror/", dependencies = TRUE)
#install.packages("knitr", repos = "https://packages.sde.digital.nhs.uk/repository/cran-mirror/", dependencies = TRUE)
#install.packages("kableExtra", repos = "https://packages.sde.digital.nhs.uk/repository/cran-mirror/", dependencies = TRUE)
#install.packages("odbc", repos = "https://packages.sde.digital.nhs.uk/repository/cran-mirror/", dependencies = TRUE)
#install.packages("DBI", repos = "https://packages.sde.digital.nhs.uk/repository/cran-mirror/", dependencies = TRUE)
#install.packages("gridExtra", repos = "https://packages.sde.digital.nhs.uk/repository/cran-mirror/", dependencies = TRUE)

#setup markdown
knitr::opts_chunk$set(echo = TRUE)

#load packages
library(tidyverse)
library(knitr)
library(kableExtra)
library(gridExtra)

#load data
library(odbc)
library(DBI)
con <- DBI::dbConnect(odbc:::odbc(), "databricks")
cohort = dbGetQuery(con, 'Select * from dsa_391419_j3w9t_collab.ccu075_01_df_final_20240822_updated') # from 07_mix_step_2_of_3 (core table of cohort)
lsoas_pre_adjusted_date = dbGetQuery(con, 'Select * from dsa_391419_j3w9t_collab.ccu075_01_lsoa_pre_adjusted_date_final_updated') # from 18_LSOA01_impute_updated
lsoas_pre_index = dbGetQuery(con, 'Select * from dsa_391419_j3w9t_collab.ccu075_01_lsoa_pre_index_date_final_updated') # from 18_LSOA01_impute_updated
DBI::dbDisconnect(con)
```

### Incident cohort

```{r incidence}
#Remove individuals less than 2 years at adjusted diagnosis date
cohort_over_2 <- cohort %>%
  mutate(HES_YEAR = ifelse(month(final_diag_date) < 4, # map to HES year
                           paste0(as.numeric(year(final_diag_date)) - 1, 
                                  "/", 
                                  str_sub(sprintf("%02d", 
                                                  as.numeric(str_sub(year(final_diag_date), 
                                                                     start= -2))), 
                                          start= -2)), 
                           paste0(as.numeric(year(final_diag_date)),
                                  "/", 
                                  str_sub(sprintf("%02d", 
                                                  as.numeric(str_sub(year(final_diag_date), 
                                                                     start= -2)) + 1), 
                                          start= -2)))) %>% 
  filter(as.numeric(final_age) >= 2) 

#Lsoa/IMD linkage
lsoas_pre_adjusted_date <- lsoas_pre_adjusted_date %>%
  select(PERSON_ID_DEID, LSOA11_curated_pre_adjusted_date, info_LSOA11_pre_adjusted_date, 
         LSOA01_curated_pre_adjusted_date, info_LSOA01_pre_adjusted_date)

cohort_over_2_with_diag_lsoas <- left_join(cohort_over_2, lsoas_pre_adjusted_date, by=c("PERSON_ID_DEID")) %>%
  mutate(diagnosis_YEAR = as.numeric(as.numeric(year(final_diag_date)))) %>%
  mutate(LSOA_inc = ifelse(diagnosis_YEAR > 2009, # previously 2010 but resulted in some failed imd linkages for people diagnosed in 2010
                           LSOA11_curated_pre_adjusted_date,
                           LSOA01_curated_pre_adjusted_date)) 

# Check imd linkage
# cohort_check <- cohort_over_2_with_diag_lsoas %>%
#   select(PERSON_ID_DEID, final_diag_date, diagnosis_YEAR, LSOA_inc) 
# head(cohort_check) # all seemed in order

#Remove non-English residents at point of diagnosis for incidence calculations
incidence_cohort_England <- cohort_over_2_with_diag_lsoas %>%
  filter(grepl("E", LSOA_inc, fixed=TRUE)) %>%
  filter(final_diag_date > "2006-03-31") %>%
  filter(final_diag_date < "2023-04-01") 

#I tested this version of the cohort to make sure the problematic patient IDs from the previous version had been corrected. All looked in order on spot checking.
```

### Consort

```{r}
#get size of prevalent cohort and then add in incidence data for CONSORT export
lsoas_pre_index <- lsoas_pre_index %>%
  select(PERSON_ID_DEID, LSOA11_curated_pre_index_date, info_LSOA11_pre_index_date)

#merge with LSOA11 at index date
cohort_over_2_with_prev_lsoas <- left_join(cohort, lsoas_pre_index, by=c("PERSON_ID_DEID")) %>% 
  filter(as.numeric(final_age) >= 2) 
#summary(cohort_over_2_with_prev_lsoas$final_age)
#unique(cohort_over_2_with_prev_lsoas$info_LSOA11_pre_index_date)

prevalence_cohort_England <- cohort_over_2_with_prev_lsoas %>%
  filter(REG_DATE_OF_DEATH > "2022-07-01" | is.na(REG_DATE_OF_DEATH)) %>%
  filter(final_diag_date <= "2022-07-01") %>%
  select(PERSON_ID_DEID, final_diag_date, REG_DATE_OF_DEATH, LSOA11_curated_pre_index_date)
#summary(prevalence_cohort_England$final_diag_date) - all before 1st July 2022
#summary(as.Date(prevalence_cohort_England$REG_DATE_OF_DEATH)) - all after 1st July 2022 and NAs

##adding this check on 3rd October as I think I left in non-English residents
#prevalence_cohort_not_England <- prevalence_cohort_England_old %>%
#filter(!grepl("E", LSOA11_curated_pre_index_date, fixed=TRUE))

# Counts for consort
# Some rows redacted where superseded by newer scripts to avoid confusion
# Unrounded counts were exported for full transparency in cohort creation. Output checkers approved this alongside the contextual information below.

consort_data <- data.frame(rbind(c("Number with ICD-10 M31.4", 
                                   length(cohort$PERSON_ID_DEID)),
                                 c("Number with ICD-10 M31.4 aged < 2 years", 
                                   length(cohort$PERSON_ID_DEID) - length(cohort_over_2$PERSON_ID_DEID)),
                                 c("Number with ICD-10 M31.4 aged >= 2 years", 
                                   length(cohort_over_2$PERSON_ID_DEID)),
                                 c("Number of incident cases from 01/04/2006 - 31/03/2023",
                                   length(incidence_cohort_England$PERSON_ID_DEID))
                                  )
                                )

consort_data %>%
  kable(booktabs=TRUE, align="l", col.names = c("Consort element",
                                                "Count"))
# setwd("D:/PhotonUser/My Files/Home Folder/ccu075_01")
# write.csv2(consort_data, "ccu075_01_consort_data_20240923.csv")

# Contextual information
# Counts to add to a CONSORT diagram for creation of our cohort (cases of Takayasu arteritis, ICD-10 M31.4)
# 
# Column 1: Description of the count
# Column 2*: Number of cases
# 
# *Indicates unrounded rates for full transparency in reporting of cohort creation. There are no unrounded rates less than 50. 
```

### Version

```{r version, echo=FALSE}
sessionInfo()
```