---
title: "Annual incidence of Takayasu Arteritis in England"
author: "Stephanie J Lax"
date: "`r Sys.Date()`"
output:
  html_document: 
    code_folding: hide
  pdf_document: default
---

```{r setup, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load packages
library(tidyverse)
library(knitr)
library(kableExtra)

# Import data
incidence_rates <- read.csv2("[redacted]~/ccu075_01_M314_incidence_per_year_20240923.csv")
```

### Annual incidence 01/04/2006 - 31/03/2023

```{r incidence_by_year}
incidence_rates %>%
  # Round and concatenate incidence rate and CI
  mutate(concatenated = paste0(sprintf("%.1f", round(Incidence.rate, 1)),
                               " (",
                               sprintf("%.1f", round(X95..CI.lower.bound, 1)),
                               ", ",
                               sprintf("%.1f", round(X95..CI.upper.bound, 1)),
                               ")"
                               )) %>%
  # Restrict to only relevant columns for output
  select(HES.Year, Number.of.incident.cases, Population.at.risk, concatenated) %>%
  # Tidy up column names and alignment etc
  kable(booktabs = TRUE, align = "l", col.names = c("HES year", 
                                                    "Number of incident cases", 
                                                    "Population", 
                                                    "Incidence rate* (95% CI)")
        )

# checks - I was suspicious in the lack of variation in the width of the CI
# incidence_rates_checks <- incidence_rates %>%
#  mutate(diff1 = X95..CI.upper.bound - Incidence.rate,
#         diff2 = Incidence.rate - X95..CI.lower.bound)
```

*Incident cases per million with 2-tailed 95% Poisson confidence interval.

NB: Cases rounded to nearest 5 to comply with disclosure control protocol.

```{r plot_by_year}
# Remove totals row
annual_incidence <- incidence_rates %>% 
  filter(HES.Year != "Total")

# Plot number of incident cases per year with 95% Poisson CI and indicating COVID-19 pandemic
ggplot(data=annual_incidence, aes(x=HES.Year)) +
  geom_col(aes(y=Number.of.incident.cases), fill="cornflowerblue", alpha=0.5) +
  geom_line(aes(y=round(Incidence.rate,1)*50, group=1), color="blue") +
  geom_errorbar(aes(ymin=round(X95..CI.lower.bound,1)*50, ymax=round(X95..CI.upper.bound,1)*50), width=0.2) +
  labs(title="Takayasu arteritis incidence per million with 95% Poisson CI", x="Year") +
  theme_bw() +
  scale_y_continuous(
    name = "Observed cases",
    sec.axis = sec_axis(transform=~./50, name="Rate per million")
  ) +
  theme(plot.title=element_text(size=10), axis.title=element_text(size=10),
        axis.text.x=element_text(size=10, angle=90, hjust=0, vjust=0.5), axis.text.y=element_text(size=10)) +
  geom_point(aes(x=HES.Year, y=round(Incidence.rate,1)*50), size=1.5) +
  geom_vline(xintercept=14.5, linetype="dashed", colour="red", linewidth=1) +
  geom_label(label="COVID-19\npandemic", x=15.55, y=100,
             label.padding=unit(0.2, "lines"), label.size=0.09, colour="black", fill="lightgoldenrodyellow")
```

### Version

```{r version}
sessionInfo()
```