---
title: "Quantifying the extent of diagnosis date refinement in an epidemiology study of Takayasu arteritis in England (incident cohort)"
author: "SJ Lax"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
  pdf_document: default
---

### Setup

```{r setup}
#install packages at first use
#install.packages("tidyverse", repos = "https://packages.sde.digital.nhs.uk/repository/cran-mirror/", dependencies = TRUE)
#install.packages("knitr", repos = "https://packages.sde.digital.nhs.uk/repository/cran-mirror/", dependencies = TRUE)
#install.packages("kableExtra", repos = "https://packages.sde.digital.nhs.uk/repository/cran-mirror/", dependencies = TRUE)

#setup markdown
knitr::opts_chunk$set(echo = TRUE)

#load packages
library(tidyverse)
library(knitr)
library(kableExtra)

setwd("D:/PhotonUser/My Files/Home Folder/ccu075_01")

# Get cohort data
incidence_cohort_England <- read.csv2("ccu075_01_M314_cohort_20240925.csv") %>%
  mutate(apc_post_covid_flag = ifelse(flag_hes_apc_tak == 1 & APC_m314_event_date >= "2020-03-11", 1, 0),
         op_post_covid_flag = ifelse(flag_hes_op_tak == 1 & OP_m314_event_date >= "2020-03-11", 1, 0)) %>%
  select(PERSON_ID_DEID, flag_hes_apc_tak, APC_m314_event_date, flag_hes_op_tak, OP_m314_event_date, APC_ICD10_CODE_date, OP_ICD10_CODE_date, OP_spec_date, final_diag_date, apc_post_covid_flag, op_post_covid_flag) %>% 
  rowwise() %>%
  mutate(earliest_m314 = min(APC_m314_event_date, OP_m314_event_date, na.rm=TRUE),
         duration = floor(-as.numeric(difftime(final_diag_date, earliest_m314, units = "days"))/365.25))
```

### Overall extent of diagnosis date refinement

```{r extent}
extent_per_person <- incidence_cohort_England %>%
  mutate(pre_covid = ifelse(earliest_m314 < "2020-03-11", 1, 0),
         extent_of_date_refinement = ifelse(duration == 0, "<1 year",
                                            ifelse(duration >= 1 & duration < 3, "1-2 years",
                                            ifelse(duration >= 3 & duration < 6, "3-5 years",
                                            ifelse(duration >= 6 & duration < 11, "6-10 years",
                                            ">10 years"))))) 

overall <- extent_per_person %>%
  group_by(extent_of_date_refinement) %>%
  summarise(n=n()) %>% 
  mutate(percentage = round(100*n/length(incidence_cohort_England$PERSON_ID_DEID)),
         rounded_n = 5*round(n/5),
         group="Overall") %>%
  select(-n)

pre_covid = extent_per_person %>%
  filter(pre_covid == 1) %>% 
  group_by(extent_of_date_refinement) %>%
  summarise(n=n()) %>% 
  mutate(percentage = round(100*n/sum(extent_per_person$pre_covid)),
         rounded_n = 5*round(n/5),
         group="Pre_covid") %>%
  select(-n)
         
post_covid = extent_per_person %>%
  filter(pre_covid == 0) %>% 
  group_by(extent_of_date_refinement) %>%
  summarise(n=n()) %>% 
  mutate(percentage = round(100*n/(length(incidence_cohort_England$PERSON_ID_DEID) - sum(extent_per_person$pre_covid))),
         rounded_n = 5*round(n/5),
         group="Post_covid") %>%
  select(-n)

to_export <- rbind(overall, pre_covid, post_covid)

#write.csv(to_export, "ccu075_01_Extent_of_diagnosis_date_refinement_20241112.csv")

# Contextual information
# Duration between first coding of likely symptoms of Takayasu arteritis (M31.4) and receiving a diagnosis
# 
# Column 1: Description of the duration between first coding of symptoms and receiving a diagnosis
# Column 2: Percentage of cases
# Column 3: Number of cases rounded to the nearest 5 with no counts less than 10
# Column 4: Group indicating whether these percentages and case numbers are overall or for M31.4 diagnoses made before of after 11th March 2020
```

### Source of earliest date

```{r source}
cohort_dates_gathered <- incidence_cohort_England %>%
  select(-c(earliest_m314, duration, apc_post_covid_flag, op_post_covid_flag, flag_hes_apc_tak, flag_hes_op_tak)) %>%
  gather("source", "date", APC_m314_event_date, OP_m314_event_date, APC_ICD10_CODE_date, OP_ICD10_CODE_date, OP_spec_date) %>%
  filter(!is.na(date),
         final_diag_date == date) 

minimum_cohort_dates_refined <- cohort_dates_gathered %>%
  select(-c(final_diag_date, date)) %>%
  group_by(PERSON_ID_DEID) %>%
  summarise(earliest_source = paste0(source, collapse = ", ")) %>%
  mutate(refined_source = ifelse(grepl("event", earliest_source), "first_m314",
                                 ifelse(grepl("OP_spec", earliest_source), "outpatient_clinic",
                                        ifelse(grepl("ICD10", earliest_source), "ICD10", "Other")))) %>%
  ungroup()

# unique(minimum_cohort_dates_refined2$refined_source) # indicates I captured the right sources

minimum_cohort_dates_refined_consolidated <- minimum_cohort_dates_refined %>%
  group_by(refined_source) %>%
  summarise(n=n(),
         rounded_n = 5*round(n/5),
         percentage = round(100*n/length(incidence_cohort_England$duration))) %>%
  arrange(desc(rounded_n)) %>%
  filter(n >= 10) %>%
  select(-n)

#write.csv(minimum_cohort_dates_refined_consolidated, "ccu075_01_source_of_earliest_TAK_dates_20250226.csv")

# Blurb for output checking
# Source of earliest indication of Takayasu arteritis (TAK diagnosis or pre-existing conditions) in HES APC or OP in England
# 
# Column 1: Description of source (either ICD10 code for TAK, m314 in HES APC or HES OP, an ICD10 code for a related pre-existing condition, or an outpatient specialty code)
# Column 2: Number of cases for whom this source was the earliest indication they had TAK, rounded to the nearest 5
# Column 3: Percentage of the total cohort of people with TAK

# Note on checks done 07/05/2025; whilst the percentages exported were calculated based on unrounded counts, they are the same as if they'd be produced based on rounded counts at this level of rounding.
```

### Version

```{r version, echo=FALSE}
sessionInfo()
```