---
title: "Incidence estimates for Takayasu arteritis in England by Demographic Group"
author: "SJ Lax"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
  pdf_document: default
---

### Setup

```{r setup}
#install packages at first use
#install.packages("tidyverse", repos = "https://packages.sde.digital.nhs.uk/repository/cran-mirror/", dependencies = TRUE)
#install.packages("knitr", repos = "https://packages.sde.digital.nhs.uk/repository/cran-mirror/", dependencies = TRUE)
#install.packages("kableExtra", repos = "https://packages.sde.digital.nhs.uk/repository/cran-mirror/", dependencies = TRUE)

#setup markdown
knitr::opts_chunk$set(echo = TRUE)

#load packages
library(tidyverse)
library(knitr)
library(kableExtra)

setwd("D:/PhotonUser/My Files/Home Folder/ccu075_01")

# Get cohort data
incidence_cohort_England <- read.csv2("ccu075_01_M314_cohort_20240925.csv")
denominators <- read.csv("ccu075_01_denominators_i_age_group_sex_region_20241014.csv")

denominators_grouped <- denominators %>%
  group_by(Code, sex, age_group) %>%
  summarise(population = sum(as.numeric(total_population))) 
#sum(denominators_grouped$population) - looks good
```

### Incident cohort: rate ratio by sex

```{r ratios}
# Set parameters for analyses
CI_level <- 0.95
rate_multiplier <- 1000000

#Compile cases and denominator dataset where age is grouped
grouped_demographics <- incidence_cohort_England %>%
  group_by(region_code, sex, age_group) %>%
  summarise(cases = n()) %>%
  ungroup() %>%
  rename(Code = region_code)

merged_grouped <- full_join(grouped_demographics, denominators_grouped, by=c("Code", "sex", "age_group")) %>%
  mutate(cases = ifelse(is.na(cases), 0, cases))

#sum(merged_grouped$cases) - OK
#sum(merged_grouped$population) - OK

### Crude rate ratios: sex
crude_inc_rates_by_sex <- merged_grouped %>%
  group_by(sex) %>%
  summarise(Cases_for_calculations = ifelse(sum(cases)>50, sum(cases), #calculates using real counts where n>50
                                ifelse(sum(cases)>9, 5*round(sum(cases)/5,0), #calculates using counts to nearest 5 where n>9/<50
                                       1)), #Suppresses percentage where count is less than 10 (to 1 to enable code to parse)
            Population=sum(population))

crude_inc_rates_by_sex$sex <- factor(crude_inc_rates_by_sex$sex, levels=c("Male", "Female"))
poisson.model_sex <- glm(formula = Cases_for_calculations ~ sex, 
                      offset = log(Population),
                      family = poisson(link="log"), 
                      data = crude_inc_rates_by_sex)
summary(poisson.model_sex)

ecm <- exp(coef(poisson.model_sex))
ci <- exp(confint(poisson.model_sex))

collated_crude_ORs <- data.frame(rbind(c(Group = "Male", OR = 1, Lower_CI = NA, Upper_CI = NA),
                                       c(Group = "Female", 
                                         OR = round(ecm[[2]],2),
                                         Lower_CI = round(ci[[2]],2), 
                                         Upper_CI = round(ci[[4]],2)
                                 )))
```

### Crude odds ratios: age

```{r incidence_odds_age, message=FALSE}
crude_inc_rates_by_age <- merged_grouped %>%
  group_by(age_group) %>%
  summarise(Cases_for_calculations = ifelse(sum(cases)>50, sum(cases), #calculates using real counts where n>50
                                            ifelse(sum(cases)>9, 5*round(sum(cases)/5,0), #calculates using counts to nearest 5 where n>9/<50
                                                   1)), #Suppresses percentage where count is less than 10 (to 1 to enable code to parse)
            Population=sum(population))

crude_inc_rates_by_age$age_group <- factor(crude_inc_rates_by_age$age_group, levels=c("16-39", 
                                                                                        "0-15", 
                                                                                        "40-54", 
                                                                                        "55-69", 
                                                                                        "70-84", 
                                                                                        "85-90"))
poisson.model_age <- glm(formula = Cases_for_calculations ~ age_group, 
                         offset = log(Population),
                         family = poisson(link="log"), 
                         data = crude_inc_rates_by_age)

summary(poisson.model_age)

ecm <- exp(coef(poisson.model_age))
ci <- exp(confint(poisson.model_age))

collated_crude_ORs <- data.frame(rbind(collated_crude_ORs,
                                       c(Group = "0-15", 
                                         OR = round(ecm[str_detect(names(ecm), pattern="0-15")][[1]],2), 
                                         Lower_CI = round(ci[str_detect(row.names(ci), pattern="0-15"),][[1]],2), 
                                         Upper_CI = round(ci[str_detect(row.names(ci), pattern="0-15"),][[2]],2)),
                                       c(Group = "16-39", 
                                         OR = 1, 
                                         Lower_CI = NA, 
                                         Upper_CI = NA),
                                       c(Group = "40-54", 
                                         OR = round(ecm[str_detect(names(ecm), pattern="40-54")][[1]],2), 
                                         Lower_CI = round(ci[str_detect(row.names(ci), pattern="40-54"),][[1]],2), 
                                         Upper_CI = round(ci[str_detect(row.names(ci), pattern="40-54"),][[2]],2)),
                                       c(Group = "55-69", 
                                         OR = round(ecm[str_detect(names(ecm), pattern="55-69")][[1]],2), 
                                         Lower_CI = round(ci[str_detect(row.names(ci), pattern="55-69"),][[1]],2), 
                                         Upper_CI = round(ci[str_detect(row.names(ci), pattern="55-69"),][[2]],2)),
                                       c(Group = "70-84", 
                                         OR = round(ecm[str_detect(names(ecm), pattern="70-84")][[1]],2), 
                                         Lower_CI = round(ci[str_detect(row.names(ci), pattern="70-84"),][[1]],2), 
                                         Upper_CI = round(ci[str_detect(row.names(ci), pattern="70-84"),][[2]],2)),
                                       c(Group = "85-90", 
                                         OR = round(ecm[str_detect(names(ecm), pattern="85-90")][[1]],2), 
                                         Lower_CI = round(ci[str_detect(row.names(ci), pattern="85-90"),][[1]],2), 
                                         Upper_CI = round(ci[str_detect(row.names(ci), pattern="85-90"),][[2]],2))
                                       )
                                 )
```

### Crude odds ratios: region

```{r incidence_odds_region, message=FALSE}
crude_inc_rates_by_region <- merged_grouped %>%
  group_by(Code) %>%
  summarise(Cases_for_calculations = ifelse(sum(cases)>50, sum(cases), #calculates using real counts where n>50
                                            ifelse(sum(cases)>9, 5*round(sum(cases)/5,0), #calculates using counts to nearest 5 where n>9/<50
                                                   1)), #Suppresses percentage where count is less than 10 (to 1 to enable code to parse)
            Population=sum(population))

crude_inc_rates_by_region$Code <- factor(crude_inc_rates_by_region$Code, levels=c("E12000007", 
                                                                                    "E12000001", 
                                                                                    "E12000002", 
                                                                                    "E12000003", 
                                                                                    "E12000004", 
                                                                                    "E12000005",
                                                                                    "E12000006",
                                                                                    "E12000008",
                                                                                    "E12000009"))
poisson.model_region <- glm(formula = Cases_for_calculations ~ Code, 
                         offset = log(Population),
                         family = poisson(link="log"), 
                         data = crude_inc_rates_by_region)

summary(poisson.model_region)

ecm <- exp(coef(poisson.model_region))
ci <- exp(confint(poisson.model_region))

collated_crude_ORs <- data.frame(rbind(collated_crude_ORs,
                                       c(Group = "E12000001", 
                                         OR = round(ecm[str_detect(names(ecm), pattern="E12000001")][[1]],2), 
                                         Lower_CI = round(ci[str_detect(row.names(ci), pattern="E12000001"),][[1]],2), 
                                         Upper_CI = round(ci[str_detect(row.names(ci), pattern="E12000001"),][[2]],2)),
                                       c(Group = "E12000002", 
                                         OR = round(ecm[str_detect(names(ecm), pattern="E12000002")][[1]],2), 
                                         Lower_CI = round(ci[str_detect(row.names(ci), pattern="E12000002"),][[1]],2), 
                                         Upper_CI = round(ci[str_detect(row.names(ci), pattern="E12000002"),][[2]],2)),
                                       c(Group = "E12000003", 
                                         OR = round(ecm[str_detect(names(ecm), pattern="E12000003")][[1]],2), 
                                         Lower_CI = round(ci[str_detect(row.names(ci), pattern="E12000003"),][[1]],2), 
                                         Upper_CI = round(ci[str_detect(row.names(ci), pattern="E12000003"),][[2]],2)),
                                       c(Group = "E12000004", 
                                         OR = round(ecm[str_detect(names(ecm), pattern="E12000004")][[1]],2), 
                                         Lower_CI = round(ci[str_detect(row.names(ci), pattern="E12000004"),][[1]],2), 
                                         Upper_CI = round(ci[str_detect(row.names(ci), pattern="E12000004"),][[2]],2)),
                                       c(Group = "E12000005", 
                                         OR = round(ecm[str_detect(names(ecm), pattern="E12000005")][[1]],2), 
                                         Lower_CI = round(ci[str_detect(row.names(ci), pattern="E12000005"),][[1]],2), 
                                         Upper_CI = round(ci[str_detect(row.names(ci), pattern="E12000005"),][[2]],2)),
                                       c(Group = "E12000006", 
                                         OR = round(ecm[str_detect(names(ecm), pattern="E12000006")][[1]],2), 
                                         Lower_CI = round(ci[str_detect(row.names(ci), pattern="E12000006"),][[1]],2), 
                                         Upper_CI = round(ci[str_detect(row.names(ci), pattern="E12000006"),][[2]],2)),
                                       c(Group = "E12000007", 
                                         OR = 1, 
                                         Lower_CI = NA, 
                                         Upper_CI = NA),
                                       c(Group = "E12000008", 
                                         OR = round(ecm[str_detect(names(ecm), pattern="E12000008")][[1]],2), 
                                         Lower_CI = round(ci[str_detect(row.names(ci), pattern="E12000008"),][[1]],2), 
                                         Upper_CI = round(ci[str_detect(row.names(ci), pattern="E12000008"),][[2]],2)),
                                       c(Group = "E12000009", 
                                         OR = round(ecm[str_detect(names(ecm), pattern="E12000009")][[1]],2), 
                                         Lower_CI = round(ci[str_detect(row.names(ci), pattern="E12000009"),][[1]],2), 
                                         Upper_CI = round(ci[str_detect(row.names(ci), pattern="E12000009"),][[2]],2)))
                                 )
```

### Adjusted odds ratios: region

```{r incidence_odds_adj, message=FALSE}
#redo variable types for ungrouped dataset
adjusted_inc_rates_by_region <- merged_grouped %>%
  mutate(Cases_for_calculations = ifelse(cases == 0, 1, cases)) #Doesn't suppress counts but resolves 0 to 1 to enable code to parse

adjusted_inc_rates_by_region$Code <- factor(adjusted_inc_rates_by_region$Code, levels=c("E12000007", 
                                                                                          "E12000001", 
                                                                                          "E12000002", 
                                                                                          "E12000003", 
                                                                                          "E12000004", 
                                                                                          "E12000005",
                                                                                          "E12000006",
                                                                                          "E12000008",
                                                                                          "E12000009"))
poisson.model_region2 <- glm(formula = Cases_for_calculations ~ Code + age_group + sex, 
                         offset = log(population),
                         family = poisson(link="log"), 
                         data = adjusted_inc_rates_by_region)

summary(poisson.model_region2)

ecm <- exp(coef(poisson.model_region2))
ci <- exp(confint(poisson.model_region2))

collated_ORs <- data.frame(rbind(collated_crude_ORs,
                                       c(Group = "E12000001*", 
                                         OR = round(ecm[str_detect(names(ecm), pattern="E12000001")][[1]],2), 
                                         Lower_CI = round(ci[str_detect(row.names(ci), pattern="E12000001"),][[1]],2), 
                                         Upper_CI = round(ci[str_detect(row.names(ci), pattern="E12000001"),][[2]],2)),
                                       c(Group = "E12000002*", 
                                         OR = round(ecm[str_detect(names(ecm), pattern="E12000002")][[1]],2), 
                                         Lower_CI = round(ci[str_detect(row.names(ci), pattern="E12000002"),][[1]],2), 
                                         Upper_CI = round(ci[str_detect(row.names(ci), pattern="E12000002"),][[2]],2)),
                                       c(Group = "E12000003*", 
                                         OR = round(ecm[str_detect(names(ecm), pattern="E12000003")][[1]],2), 
                                         Lower_CI = round(ci[str_detect(row.names(ci), pattern="E12000003"),][[1]],2), 
                                         Upper_CI = round(ci[str_detect(row.names(ci), pattern="E12000003"),][[2]],2)),
                                       c(Group = "E12000004*", 
                                         OR = round(ecm[str_detect(names(ecm), pattern="E12000004")][[1]],2), 
                                         Lower_CI = round(ci[str_detect(row.names(ci), pattern="E12000004"),][[1]],2), 
                                         Upper_CI = round(ci[str_detect(row.names(ci), pattern="E12000004"),][[2]],2)),
                                       c(Group = "E12000005*", 
                                         OR = round(ecm[str_detect(names(ecm), pattern="E12000005")][[1]],2), 
                                         Lower_CI = round(ci[str_detect(row.names(ci), pattern="E12000005"),][[1]],2), 
                                         Upper_CI = round(ci[str_detect(row.names(ci), pattern="E12000005"),][[2]],2)),
                                       c(Group = "E12000006*", 
                                         OR = round(ecm[str_detect(names(ecm), pattern="E12000006")][[1]],2), 
                                         Lower_CI = round(ci[str_detect(row.names(ci), pattern="E12000006"),][[1]],2), 
                                         Upper_CI = round(ci[str_detect(row.names(ci), pattern="E12000006"),][[2]],2)),
                                       c(Group = "E12000007*", 
                                         OR = 1, 
                                         Lower_CI = NA, 
                                         Upper_CI = NA),
                                       c(Group = "E12000008*", 
                                         OR = round(ecm[str_detect(names(ecm), pattern="E12000008")][[1]],2), 
                                         Lower_CI = round(ci[str_detect(row.names(ci), pattern="E12000008"),][[1]],2), 
                                         Upper_CI = round(ci[str_detect(row.names(ci), pattern="E12000008"),][[2]],2)),
                                       c(Group = "E12000009*", 
                                         OR = round(ecm[str_detect(names(ecm), pattern="E12000009")][[1]],2), 
                                         Lower_CI = round(ci[str_detect(row.names(ci), pattern="E12000009"),][[1]],2), 
                                         Upper_CI = round(ci[str_detect(row.names(ci), pattern="E12000009"),][[2]],2)))
                                 )
```

```{R export}
#Print table
collated_ORs %>%
  kable(booktabs=TRUE, align="l", col.names = c("Group", 
                       "Odds ratio", 
                       "95% CI lower bound",
                       "95% CI upper bound"))

#write.csv(collated_ORs, "ccu075_01_M314_inc_ratios_age_sex_region_20241016.csv")

# Contextual information
# Crude and adjusted odds ratios for incidence of Takayasu arteritis by demographic group
# 
# Column 1: Group (sex, age group, or Government Office Region code). Asterisk indicates ratios adjusted for age and sex, otherwise the estimates given are crude
# Column 2: Odds ratio of diagnosis with Takayasu arteritis within each demographic group (1 indicates reference group)
# Column 3: Poisson 95% confidence interval lower bound
# Column 4: Poisson 95% confidence interval upper bound
```

### Version

```{r version, echo=FALSE}
sessionInfo()
```