---
title: "Prevalence estimates for Takayasu arteritis in England by Demographic Group"
author: "SJ Lax"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
  pdf_document: default
---

### Setup

```{r setup}
#install packages at first use
#install.packages("tidyverse", repos = "https://packages.sde.digital.nhs.uk/repository/cran-mirror/", dependencies = TRUE)
#install.packages("knitr", repos = "https://packages.sde.digital.nhs.uk/repository/cran-mirror/", dependencies = TRUE)
#install.packages("kableExtra", repos = "https://packages.sde.digital.nhs.uk/repository/cran-mirror/", dependencies = TRUE)

#setup markdown
knitr::opts_chunk$set(echo = TRUE)

#load packages
library(tidyverse)
library(knitr)
library(kableExtra)

setwd("D:/PhotonUser/My Files/Home Folder/ccu075_01")

# Get cohort and denominator data
prevalence_cohort_England <- read.csv2("ccu075_01_M314_p_cohort_20241007.csv")
denominators_2022 <- read.csv("ccu075_01_denominators_age_group_sex_ethnicity_20241009.csv")
```

### Prevalent cohort: crude rate ratio by ethnicity

```{r ratios}
# Set parameters for analyses
CI_level <- 0.95
rate_multiplier <- 1000000

#Compile cases and denominator dataset where age is grouped
grouped_demographics <- prevalence_cohort_England %>%
  select(-age_group) %>%
  group_by(Eth_grouped, sex, age_group_index) %>%
  summarise(cases = n()) %>%
  ungroup() %>%
  rename(age_group = age_group_index,
         ethnicity = Eth_grouped)

denominators_2022_grouped <- denominators_2022 %>%
  group_by(ethnicity, sex, age_group) %>%
  summarise(population = sum(as.numeric(Population)))

#sum(denominators_2022_grouped$population) # approximately comparable for best estimates

merged_grouped <- full_join(grouped_demographics, denominators_2022_grouped, by=c("ethnicity", "sex", "age_group")) %>%
  mutate(cases = ifelse(is.na(cases), 0, cases))

#sum(merged_grouped$population, na.rm=TRUE)
#sum(merged_grouped$cases)
```

### Crude prevalence rates by ethnicity

```{r crude_rates}
crude_prev_rates_by_ethnicity <- merged_grouped %>%
  group_by(ethnicity) %>%
  summarise(Cases_to_publish = ifelse(sum(cases)>9, 5*round(sum(cases)/5,0), 0),
            Cases_for_calculations = ifelse(sum(cases)>50, sum(cases), #calculates using real counts where n>50
                                ifelse(sum(cases)>9, 5*round(sum(cases)/5,0), #calculates using counts to nearest 5 where n>9/<50
                                       0)), #Suppresses percentage where count is less than 10
            Percentage_to_publish = ifelse(sum(cases)>50, round(100*(sum(cases)/length(prevalence_cohort_England[,1])),1), #calculates percentage using real counts where n>50
                                ifelse(sum(cases)>9, round(100*(5*round(sum(cases)/5,0)/length(prevalence_cohort_England[,1])),1), #calculates percentage using counts to nearest 5 where n>9/<50
                                       paste0("<", round(100*(10/length(prevalence_cohort_England[,1]))),1))), #Suppresses percentage where count is less than 10
            Population=sum(population, na.rm=TRUE),
            Crude_prevalence = Cases_for_calculations/sum(population, na.rm=TRUE)*rate_multiplier,
            Lower_limit = poisson.test(Cases_for_calculations,conf.level = CI_level)$conf.int[1]/sum(population, na.rm=TRUE)*rate_multiplier,
            Upper_limit = poisson.test(Cases_for_calculations,conf.level = CI_level)$conf.int[2]/sum(population, na.rm=TRUE)*rate_multiplier)

#Combine and export
crude_prev_rates <- crude_prev_rates_by_ethnicity %>%
  select(ethnicity, Cases_to_publish, Percentage_to_publish, Population, Crude_prevalence, Lower_limit, Upper_limit)

#Print table
crude_prev_rates %>%
  kable(booktabs=TRUE, align="l", col.names = c("Ethnicity", 
                       "Number of prevalent cases", 
                       "Percentage of total", 
                       "Population",
                       "Crude prevalence*", 
                       "95% CI lower bound",
                       "95% CI upper bound"))

#write.csv(crude_prev_rates, "ccu075_01_M314_prev_rates_per_m_eth_20241009.csv")

# Contextual information
# Crude prevalence of Takayasu arteritis by ethnicity: 1st July 2022
# 
# Column 1: Broad category of ethnicity
# Column 2: Number of cases of Takayasu arteritis (M31.4) rounded to the nearest 5, with no values less than 10
# Column 3: Percentage of total cases calculated using raw counts when >50, counts rounded to nearest 5 when >9 AND <50, and suppressed when <9
# Column 4: Population count based on publicly available data (Office of National Statistics)
# Column 5*: Crude prevalence rate derived from the unrounded counts used to produce column 3/Population in column 4*1,000,000.
# Column 6*: Poisson 95% confidence interval lower bound
# Column 7*: Poisson 95% confidence interval upper bound
```

### Crude prevalence ratios by ethnicity

```{r prevalence_odds_IMD, message=FALSE}
crude_prev_rates_by_ethnicity2 <- merged_grouped %>%
  filter(ethnicity != "Unknown") %>%
  group_by(ethnicity) %>%
  summarise(Cases_for_calculations = ifelse(sum(cases)>50, sum(cases), #calculates using real counts where n>50
                                            ifelse(sum(cases)>9, 5*round(sum(cases)/5,0), #calculates using counts to nearest 5 where n>9/<50
                                                   1)), #Suppresses percentage where count is less than 10 (to 1 to enable code to parse)
            Population=sum(population)) 

crude_prev_rates_by_ethnicity2$ethnicity <- factor(crude_prev_rates_by_ethnicity2$ethnicity, levels=c("White", 
                                                                                                    "Asian", 
                                                                                                    "Black", 
                                                                                                    "Mixed", 
                                                                                                    "Other"))

poisson.model_ethnicity <- glm(formula = Cases_for_calculations ~ ethnicity, 
                         offset = log(Population),
                         family = poisson(link="log"), 
                         data = crude_prev_rates_by_ethnicity2)

summary(poisson.model_ethnicity)

ecm <- exp(coef(poisson.model_ethnicity))
ci <- exp(confint(poisson.model_ethnicity))

collated_crude_ORs <- data.frame(rbind(c(Group = "Asian", 
                                         OR = round(ecm[str_detect(names(ecm), pattern="Asian")][[1]],2), 
                                         Lower_CI = round(ci[str_detect(row.names(ci), pattern="Asian"),][[1]],2), 
                                         Upper_CI = round(ci[str_detect(row.names(ci), pattern="Asian"),][[2]],2)),
                                       c(Group = "Black", 
                                         OR = round(ecm[str_detect(names(ecm), pattern="Black")][[1]],2), 
                                         Lower_CI = round(ci[str_detect(row.names(ci), pattern="Black"),][[1]],2), 
                                         Upper_CI = round(ci[str_detect(row.names(ci), pattern="Black"),][[2]],2)),
                                       c(Group = "Mixed", 
                                         OR = round(ecm[str_detect(names(ecm), pattern="Mixed")][[1]],2), 
                                         Lower_CI = round(ci[str_detect(row.names(ci), pattern="Mixed"),][[1]],2), 
                                         Upper_CI = round(ci[str_detect(row.names(ci), pattern="Mixed"),][[2]],2)),
                                       c(Group = "White", 
                                         OR = 1, 
                                         Lower_CI = NA, 
                                         Upper_CI = NA),
                                       c(Group = "Other", 
                                         OR = round(ecm[str_detect(names(ecm), pattern="Other")][[1]],2), 
                                         Lower_CI = round(ci[str_detect(row.names(ci), pattern="Other"),][[1]],2), 
                                         Upper_CI = round(ci[str_detect(row.names(ci), pattern="Other"),][[2]],2))
                                 )
                           )
```

### Adjusted prevalence ratios by ethnicity

```{r prevalence_odds_adj, message=FALSE}
adjusted_prev_rates_by_region <- merged_grouped %>%
  filter(ethnicity != "Unknown") %>%
  mutate(Cases_for_calculations = ifelse(cases == 0, 1, cases)) #Doesn't suppress counts but resolves 0 to 1 to enable code to parse

adjusted_prev_rates_by_region$ethnicity <- factor(adjusted_prev_rates_by_region$ethnicity, levels=c("White", 
                                                                                                    "Asian", 
                                                                                                    "Black", 
                                                                                                    "Mixed", 
                                                                                                    "Other"))

poisson.model_region2 <- glm(formula = Cases_for_calculations ~ ethnicity + age_group + sex, 
                         offset = log(population),
                         family = poisson(link="log"), 
                         data = adjusted_prev_rates_by_region)

summary(poisson.model_region2)

ecm <- exp(coef(poisson.model_region2))
ci <- exp(confint(poisson.model_region2))

collated_ORs <- data.frame(rbind(collated_crude_ORs,
                                       c(Group = "Asian*", 
                                         OR = round(ecm[str_detect(names(ecm), pattern="Asian")][[1]],2), 
                                         Lower_CI = round(ci[str_detect(row.names(ci), pattern="Asian"),][[1]],2), 
                                         Upper_CI = round(ci[str_detect(row.names(ci), pattern="Asian"),][[2]],2)),
                                       c(Group = "Black*", 
                                         OR = round(ecm[str_detect(names(ecm), pattern="Black")][[1]],2), 
                                         Lower_CI = round(ci[str_detect(row.names(ci), pattern="Black"),][[1]],2), 
                                         Upper_CI = round(ci[str_detect(row.names(ci), pattern="Black"),][[2]],2)),
                                       c(Group = "Mixed*", 
                                         OR = round(ecm[str_detect(names(ecm), pattern="Mixed")][[1]],2), 
                                         Lower_CI = round(ci[str_detect(row.names(ci), pattern="Mixed"),][[1]],2), 
                                         Upper_CI = round(ci[str_detect(row.names(ci), pattern="Mixed"),][[2]],2)),
                                       c(Group = "White*", 
                                         OR = 1, 
                                         Lower_CI = NA, 
                                         Upper_CI = NA),
                                       c(Group = "Other*", 
                                         OR = round(ecm[str_detect(names(ecm), pattern="Other")][[1]],2), 
                                         Lower_CI = round(ci[str_detect(row.names(ci), pattern="Other"),][[1]],2), 
                                         Upper_CI = round(ci[str_detect(row.names(ci), pattern="Other"),][[2]],2))
                                 )
                           )
```

```{R export}
#Print table
collated_ORs %>%
  kable(booktabs=TRUE, align="l", col.names = c("Group", 
                       "Odds ratio", 
                       "95% CI lower bound",
                       "95% CI upper bound"))

#write.csv(collated_ORs, "ccu075_01_M314_prev_ratios_ethnicity_20241009.csv")

# Contextual information
# Crude and adjusted prevalence rate ratios for Takayasu arteritis by demographic group: 1st July 2022
# 
# Column 1: Ethnicity. Asterisk indicates ratios adjusted for age and sex, otherwise the estimates given are crude
# Column 2: Odds ratio of diagnosis with Takayasu arteritis within each demographic group (1 indicates reference group)
# Column 3: Poisson 95% confidence interval lower bound
# Column 4: Poisson 95% confidence interval upper bound
```

### Version

```{r version, echo=FALSE}
sessionInfo()
```