---
title: "Median ages of incident cases of Takayasu arteritis in England by demographic group"
author: "SJ Lax"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
  pdf_document: default
---

### Setup

```{r setup}
#install packages at first use
#install.packages("tidyverse", repos = "https://packages.sde.digital.nhs.uk/repository/cran-mirror/", dependencies = TRUE)
#install.packages("knitr", repos = "https://packages.sde.digital.nhs.uk/repository/cran-mirror/", dependencies = TRUE)
#install.packages("kableExtra", repos = "https://packages.sde.digital.nhs.uk/repository/cran-mirror/", dependencies = TRUE)

#setup markdown
knitr::opts_chunk$set(echo = TRUE)

#load packages
library(tidyverse)
library(knitr)
library(kableExtra)

incidence_cohort_England <- read.csv2("ccu075_01_M314_cohort_20240925.csv")
```

### Demographics of incident cases 01/04/2006 - 31/03/2023

```{r demographics}
overall_counts <- incidence_cohort_England %>%
  summarise(Group = "Overall", 
            Cases = ifelse(n()>9, 5*round(n()/5,0), "<10"), 
            Median = median(final_age),
            IQR1 = quantile(final_age, 0.25),
            IQR3 = quantile(final_age, 0.75))

counts_by_sex <- incidence_cohort_England %>%
  group_by(sex) %>%
  summarise(Cases = ifelse(n()>9, 5*round(n()/5,0), "<10"), 
            Median = median(final_age),
            IQR1 = quantile(final_age, 0.25),
            IQR3 = quantile(final_age, 0.75)) %>%
  rename(Group = sex)

counts_by_ethnicity <- incidence_cohort_England %>%
  group_by(Eth_grouped) %>%
  summarise(Cases = ifelse(n()>9, 5*round(n()/5,0), "<10"),
            Median = median(final_age),
            IQR1 = quantile(final_age, 0.25),
            IQR3 = quantile(final_age, 0.75)) %>%
  rename(Group = Eth_grouped)

counts_by_imd <- incidence_cohort_England %>%
  group_by(imd_incidence) %>%
  summarise(Cases = ifelse(n()>9, 5*round(n()/5,0), "<10"), 
            Median = median(final_age),
            IQR1 = quantile(final_age, 0.25),
            IQR3 = quantile(final_age, 0.75)) %>%
  rename(Group = imd_incidence)

counts_by_region <- incidence_cohort_England %>%
  group_by(region_name) %>%
  summarise(Cases = ifelse(n()>9, 5*round(n()/5,0), "<10"), 
            Median = median(final_age),
            IQR1 = quantile(final_age, 0.25),
            IQR3 = quantile(final_age, 0.75)) %>%
  rename(Group = region_name)
  
Table_2 <- rbind(overall_counts, counts_by_sex, counts_by_ethnicity, counts_by_imd, counts_by_region)

Table_2 %>% kable(booktabs=TRUE, align="l")

# setwd("D:/PhotonUser/My Files/Home Folder/ccu075_01")
# write.csv(Table_2, "ccu075_01_M314_median_ages_20241211.csv")

# Contextual information
# Demographics of the incident cases of Takayasu arteritis between HES years 2006/7 to 2022/23
# 
# Column 1: Group
# Column 2: Number of cases of Takayasu arteritis (M31.4) rounded to the nearest 5, with no values less than 10
# Column 3: Median age of cases
# Column 4: Lower bound of IQR of age of cases
# Column 5: Upper bound of IQR of age of cases
```

NB: Sex is current gender of patient as recorded in HES, i.e., phenotypical rather than genotypical. Counts rounded to nearest 5 to comply with disclosure control protocol.

### Version

```{r version, echo=FALSE}
sessionInfo()
```