---
title: "Prevalence estimates for Takayasu arteritis in England by Demographic Group"
author: "SJ Lax"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
  pdf_document: default
---

### Setup

```{r setup}
#install packages at first use
#install.packages("tidyverse", repos = "https://packages.sde.digital.nhs.uk/repository/cran-mirror/", dependencies = TRUE)
#install.packages("knitr", repos = "https://packages.sde.digital.nhs.uk/repository/cran-mirror/", dependencies = TRUE)
#install.packages("kableExtra", repos = "https://packages.sde.digital.nhs.uk/repository/cran-mirror/", dependencies = TRUE)
#install.packages("MASS", repos = "https://packages.sde.digital.nhs.uk/repository/cran-mirror/", dependencies = TRUE)
#install.packages("lmtest", repos = "https://packages.sde.digital.nhs.uk/repository/cran-mirror/", dependencies = TRUE)

#setup markdown
knitr::opts_chunk$set(echo = TRUE)

#load packages
library(tidyverse)
library(knitr)
library(kableExtra)
library(MASS)
library(lmtest)

setwd("D:/PhotonUser/My Files/Home Folder/ccu075_01")

# Get cohort and denominator data
prevalence_cohort_England <- read.csv2("ccu075_01_M314_p_cohort_20241007.csv")
denominators_2022 <- read.csv("ccu075_01_denominators_age_group_sex_ethnicity_20241009.csv")

# Set parameters for analyses
CI_level <- 0.95
rate_multiplier <- 1000000

grouped_demographics <- prevalence_cohort_England %>%
  dplyr::select(-age_group) %>% # 18/02/2025 added dplyr:: to counter Error in select(., ) : unused argument ()
  group_by(Eth_grouped, sex, age_group_index) %>%
  summarise(cases = n()) %>%
  ungroup() %>%
  rename(age_group = age_group_index,
         ethnicity = Eth_grouped)

#unique(grouped_demographics$ethnicity) - no more unknowns

denominators_2022_grouped <- denominators_2022 %>%
  group_by(ethnicity, sex, age_group) %>%
  summarise(population = sum(as.numeric(Population)))

merged_grouped <- full_join(grouped_demographics, denominators_2022_grouped, by=c("ethnicity", "sex", "age_group")) %>%
  mutate(cases = ifelse(is.na(cases), 0, cases))
```


### Counts relating to age and ethnicity

```{r incidence_odds_eth_int, message=FALSE}
adjusted_prev_counts_by_ethnicity <- merged_grouped %>%
  mutate(Cases_for_counting = ifelse(is.na(cases), 0, cases),
         Population_for_counting = ifelse(is.na(population), 0, population)) %>%
  mutate(ethnicity_binary = ifelse(ethnicity == "White", "White", "non-White")) %>%
  group_by(ethnicity_binary, age_group) %>%
  summarise(n=sum(Cases_for_counting),
            population=sum(Population_for_counting)) %>%
  ungroup() %>%
  mutate(n_rounded = ifelse(n>9, 5*round(n/5, 0), "suppressed")) 

adjusted_prev_counts_by_ethnicity2 <- adjusted_prev_counts_by_ethnicity[,c(1,2,4,5)]

#write.csv(adjusted_prev_counts_by_ethnicity2, "ccu075_01_M314_prev_counts_ethnicity_age_sex_20250311.csv")

# Contextual information
# Counts of prevalent cases of Takayasu arteritis by demographic group
# 
# Column 1: Binary category of ethnicity
# Column 2: Age group
# Column 3: Population estimate (derived from publicly available ONS data)
# Column 4: Number of cases of TAK, rounded to the nearest 5 with values less than 10 suppressed
```

### Version

```{r version, echo=FALSE}
sessionInfo()
```