---
title: "Prevalence of TAK by age, sex, and region: supplementary coefficients"
author: "Stephanie J Lax"
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: hide
  
---

```{r setup, include=FALSE}
#setup markdown
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(knitr)
library(kableExtra)

#set working directory
setwd("C:/Users/mszsjl3/OneDrive - The University of Nottingham/RECORDER/Takayasu arteritis/CVD-COVID-IMPACT project proposal/Analyses")
```

### Data

```{r regional_TAK_prevalence}
prevalence_data <- read.csv2("C:/Users/mszsjl3/OneDrive - The University of Nottingham/RECORDER/Takayasu arteritis/CVD-COVID-IMPACT project proposal/Exported_data/ccu075_01_M314_prev_ratios_age_sex_region_20250203.csv") %>%
  select(-X) 

# write.csv(prevalence_data, "20250203_Prevalence_by_age_sex_region.csv")
```

*NB: Counts rounded to nearest 5 to comply with NHSE disclosure controls. Total cases rounded based on the sum of the unrounded counts.*

### Version

```{r version}
sessionInfo()
```